apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml
  - grafana-ingress.yaml
  - jenkins-ingress.yaml
  - loki-ingress.yaml
  - gitea-ingress.yaml
  - todomaster-ingress.yaml